server:
  port: 8081
spring:
# mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Softsuave@123
    url: jdbc:mysql://localhost:3306/music-video
#    jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true