server:
  port: 8081
spring:
  application:
    name: USER
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Softsuave@123
    url: jdbc:mysql://localhost:3306/ms-user
#    jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
