server:
  port: 8080
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
#          uri: http://localhost:8081/
          uri: lb://USER/
          predicates:
            - Path=/user/**

        - id: MOVIES-SERVICE
#          uri: http://localhost:8082/
          uri: lb://MOVIES/
          predicates:
            - Path=/movies/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
