server:
  port: 8082
spring:
  application:
    name: MOVIES
  datasource:
    url: jdbc:mysql://localhost:3306/ms-user
    username: root
    password: Softsuave@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka